monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event", "!security", "!request"]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info
        security_logging:
            type: rotating_file
            max_files: 10
            path: "%kernel.logs_dir%/%kernel.environment%.security.log"
            level: info
            channels: ['security']
        site_logging:
            type: rotating_file
            max_files: 10
            path: "%kernel.logs_dir%/%kernel.environment%.site.log"
            level: debug
            channels: ['request']
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
