site_list:
  path: /api/v1/check
  controller: App\Controller\SitesController::index
  methods: [GET]
site_create:
  path: /api/v1/check
  controller: App\Controller\SitesController::create
  methods: [POST]
